### ISSUE TITLE
add chainId selector to generate chain specific checksum

### ISSUE THREAD

**Issue by gasolin** [PaulRBerg/ethsum#5]
evaluate if worth to support EIP-1191 (add chain id to mixed-case checksum address)
ethereum/EIPs#1121

basically, it encodes the `chain id + address` so it helps user not to deposit token to the wrong chain address

**Comment by ricmoo** [comment]
I’ve outlined on the EIP discussions why it is not advisable to incorporate it, and there has been some discussions whether support in existing libraries will remove it; I’ve recommended against removing it (even though I’m against the EIP) from Web3.js and EthereumJS for the same reason: it impacts backwards compatibility.

But we should not go adding it to any new libraries. :)

**Comment by gasolin** [comment]
close the issue based on above comment

**Comment by juli** [comment]
Hi @gasolin I think it is a good idea (but not perfect) and the arguments in the long discussion referenced are contradictory. I can chat with you if you are interested.
